pipeline:
  identifier: Build_pchakri123_go_pipeline_sample_1747046602849
  name: Build go-pipeline-sample
  orgIdentifier: WiproPOC
  projectIdentifier: Chakri_P
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: pchakri123/go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Docker_connect
                    repo: sample_application
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
